services:
  producer-history:
    container_name: producer-history
    image: producer-history
    build:
      context: .
      dockerfile: Dockerfile-producer
    volumes:
      - ./input:/app/input
    networks:
      - kafka-net
    environment:
      OUTPUT_TOPIC: "history"
      DEAD_LETTER_QUEUE: "dlq"
      INPUT_FILE_PATH: "input/history.csv"

  processor-history:
    container_name: processor-history
    image: processor-history
    build:
      context: .
      dockerfile: Dockerfile-processor
    ports:
      - 8080:8080
    networks:
      - kafka-net
    environment:
      INPUT_TOPIC: "history"
      APP_ID: "history-processor"
    depends_on:
      - producer-history

networks:
  kafka-net:
    name: kafka-net
    driver: bridge