# Stage 1: Build the application
FROM gradle:8.13.0-jdk17-alpine AS build
WORKDIR /app

# Copy the Gradle wrapper and build files
COPY gradlew .
COPY gradle ./gradle

# Copy the build configuration and source code
COPY ./kafka-streams-processor ./

# Build the application
RUN ./gradlew build

# Stage 2: Create the runtime image
FROM openjdk:17-jdk-slim
WORKDIR /app

# Copy the JAR file from the build stage
COPY --from=build /app/build/libs/*-SNAPSHOT.jar processor-history.jar

ENV INPUT_TOPIC="history"
ENV BOOTSTRAP_SERVERS="broker-1:19092, broker-2:19092, broker-3:19092"
ENV CONSUMER_GROUP="domain-count-processor"

# Run the application
ENTRYPOINT ["java", "-jar", "processor-history.jar"]