services:
  producer-history:
    container_name: producer-history
    image: producer-history
    build:
      context: .
      dockerfile: Dockerfile-producer
    volumes:
      - ./input:/app/input
    networks:
      - kafka-net
    environment:
      OUTPUT_TOPIC: "history"
      DEAD_LETTER_QUEUE: "dlq"
      INPUT_FILE_PATH: "input/history.csv"
#    depends_on:
#      - report-reddits
#      - consumer-reddits

#  consumer-reddits:
#    container_name: consumer-reddits
#    image: consumer-reddits
#    build:
#      context: .
#      dockerfile: Dockerfile-consumer
#    networks:
#      - kafka-net
#    environment:
#      INPUT_TOPIC: "subreddits"
#      OUTPUT_TOPIC: "metric"
#      TEST_NAME: "test1"
#
#
#  report-reddits:
#    container_name: report-reddits
#    image: report-reddits
#    build:
#      context: .
#      dockerfile: Dockerfile-report
#    networks:
#      - kafka-net
#    environment:
#      INPUT_TOPIC: "metric"

networks:
  kafka-net:
    name: kafka-net
    driver: bridge